Onda_file_parsing
Orchard-Ultrasound-Innovation/HydrophoneCalibrations.jl pull request #19
Opened 2022-09-07 21:19 UTC by mofii

A complete refactor of calibatrion loading using parse_onda()

The loading is now robust against different line endings (the motivator for this refactor)

The preamp gain (0 dB or 20 dB) is now specified in the calibration filename.

2022-09-17 00:06 UTC, stevenaleung requested changes
Nice refactor. Small change requested

2022-09-22 05:39 UTC, mofii commented on src/onda_file_parsing.jl
> +    info["device_name"] = create_device_name(info)
Yup. Done

2022-09-22 18:05 UTC, stevenaleung approved these changes
Looks good. Has room for a small future refactor

2022-09-22 18:05 UTC, stevenaleung commented on src/onda_file_parsing.jl
> +    nlines = info["n_header_lines"]
Could refactor this to `nlines = get_num_header_lines(info)`

2022-09-22 18:05 UTC, stevenaleung commented on src/onda_file_parsing.jl
> +    #data_in = info["data_in"] #, n_header_lines)
Let's remove this commented line

2022-09-23 06:45 UTC, merged