Units and link capacitance
Orchard-Ultrasound-Innovation/HydrophoneCalibrations.jl pull request #29
Opened 2022-10-13 00:35 UTC by mofii

This is a breaking change that adds units within the calibration files and adds an optional input parameter for setting the hydrophone to pream link capacitance.

2022-10-13 01:20 UTC, stevenaleung requested changes
Would you mind splitting this into two PRs?

2022-10-13 01:20 UTC, stevenaleung commented on src/onda_file_parsing.jl
>          store_field(info, "Calibration_DATE", line)
Small naming inconsistency in line 42

2022-10-14 06:04 UTC, mofii commented on src/onda_file_parsing.jl
>          store_field(info, "Calibration_DATE", line)
It's Onda that defines parameter naming convention 🤷‍♂️

2022-10-14 06:07 UTC, mofii commented on calibration/calibration_example_hydrophone.jl
> +    [2.95u"MHz", 3.0u"MHz", 3.05u"MHz", 3.1u"MHz", 3.15u"MHz", 3.2u"MHz", 3.25u"MHz", 3.3u"MHz", 3.35u"MHz", 3.4u"MHz", 3.45u"MHz", 3.5u"MHz", 3.55u"MHz", 3.6u"MHz", 3.65u"MHz", 3.7u"MHz", 3.75u"MHz"
It would lead to much more complex code when writing the file if we write column vectors instead of row vectors. 
I guess I don't see the need for manually reading this file? In the future this could be a JLD2 file instead of a .jl file and then we wouldn't be able to see a thing. But in both cases they can be loaded and the data easily visualized.

2022-10-14 18:03 UTC, stevenaleung commented on src/onda_file_parsing.jl
>          store_field(info, "Calibration_DATE", line)
Ah I see, got it

2022-10-17 19:11 UTC, mofii commented on src/onda_file_parsing.jl
> +        store_field(info, "AMP_CAL_DATE", line)
Fixed in: 272b538: onda_file_parsing: Remove dublicate line

2022-10-17 19:11 UTC, mofii commented on src/onda_file_parsing.jl
> +            #println("$field: $(columns)")
Fixed in: 9a98b32: Delete commented out lines

2022-10-17 19:13 UTC, mofii commented on src/onda_file_parsing.jl
> +    format_mfg!(info)
Fixed in: 8ee3b9a: Rename format_mfg!() to format_manufacturing!()

2022-10-17 19:31 UTC, mofii commented
I need this code. Merging now, handling issues later..

2022-10-17 19:33 UTC, merged